from pydantic import BaseModel
from typing import Optional

# This defines what data is REQUIRED when someone creates a new product.
class ProductCreate(BaseModel):
    name: str
    sku: str
    description: Optional[str] = None   # optional field
    price: float

# This defines what data we SEND BACK in a response.
# It includes 'id' since that's generated by the database, not sent by the user.
class ProductResponse(BaseModel):
    id: int
    name: str
    sku: str
    description: Optional[str] = None
    price: float

    class Config:
        from_attributes = True   # allows this to read data directly from SQLAlchemy objects

# ---------- INVENTORY SCHEMAS ----------

class InventoryCreate(BaseModel):
    product_id: int
    quantity: int
    location: Optional[str] = None


class InventoryResponse(BaseModel):
    id: int
    product_id: int
    quantity: int
    location: Optional[str] = None

    class Config:
        from_attributes = True

# ---------- CUSTOMER SCHEMAS ----------

class CustomerCreate(BaseModel):
    name: str
    email: str
    phone: Optional[str] = None
    address: Optional[str] = None


class CustomerResponse(BaseModel):
    id: int
    name: str
    email: str
    phone: Optional[str] = None
    address: Optional[str] = None

    class Config:
        from_attributes = True

from datetime import datetime


# ---------- ORDER SCHEMAS ----------

# This represents ONE line item when creating an order (product + quantity)
class OrderItemCreate(BaseModel):
    product_id: int
    quantity: int


# This is what the client sends to create a full order:
# a customer_id, plus a LIST of items
class OrderCreate(BaseModel):
    customer_id: int
    items: list[OrderItemCreate]


# What we send back for a single order item (includes its own id)
class OrderItemResponse(BaseModel):
    id: int
    product_id: int
    quantity: int

    class Config:
        from_attributes = True


# What we send back for a full order, including its nested items
class OrderResponse(BaseModel):
    id: int
    customer_id: int
    status: str
    created_at: datetime
    items: list[OrderItemResponse]

    class Config:
        from_attributes = True